# Generated by Django 3.0 on 2023-09-03 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tage', models.IntegerField()),
                ('tgr', models.CharField(choices=[('k', 'Select Your Gender'), ('M', 'Male'), ('F', 'Female')], default='k', max_length=5)),
                ('tbranch', models.CharField(choices=[('G', '----- Select Branch -----'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil Engineering')], default='G', max_length=6)),
                ('tsubject', models.CharField(max_length=8)),
                ('texpr', models.IntegerField()),
                ('tdesg', models.CharField(max_length=10)),
                ('tstatus', models.BooleanField(default=0)),
                ('tch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('sgr', models.CharField(choices=[('h', 'Select Your Gender'), ('M', 'Male'), ('F', 'Female')], default='h', max_length=5)),
                ('sclass', models.CharField(choices=[(0, '----- Select class -----'), (1, '1st class'), (2, '2nd class'), (3, '3rd class'), (4, '4th class'), (5, '5th class'), (6, '6th class'), (7, '7th class'), (8, '8th class'), (9, '9th class'), (10, '10th class')], default='0', max_length=12)),
                ('sstatus', models.BooleanField(default=0)),
                ('std', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
