# Generated by Django 3.0 on 2023-09-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='tbranch',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='tsubject',
            field=models.CharField(choices=[('L', '---select the subject---'), ('MATHS', 'mathamatics'), ('PHY', 'physics'), ('SC', 'Social'), ('ENG', 'English'), ('HND', 'Hindi')], default='L', max_length=6),
        ),
    ]
