# Generated by Django 3.0 on 2023-09-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0003_auto_20230903_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='tsubject',
            field=models.CharField(choices=[('L', '---select the subject---'), ('MATHS', 'mathamatics'), ('PHY', 'physics'), ('BIO', 'Biology'), ('SC', 'Social'), ('ENG', 'English'), ('HND', 'Hindi')], default='L', max_length=6),
        ),
    ]
