# Generated by Django 3.0 on 2023-09-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0012_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='biology',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='eng',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='hindi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='phy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='social',
            field=models.IntegerField(),
        ),
    ]
