# Generated by Django 3.0 on 2023-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0013_auto_20230919_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semail',
            field=models.CharField(max_length=30),
        ),
    ]
